services:
    frontend:
        image: planty/frontend
        restart: always
        ports:
            - "3000:3000"
        environment:
            - CHOKIDAR_USEPOLLING=true
            - REACT_APP_API_SERVER=${REACT_APP_API_SERVER}
        volumes:
            - ./frontend:/app
            - /app/node_modules
        networks:
            - webappnetwork
    backend:
        image: planty/backend
        restart: always
        ports:
            - "5000:5000"
        environment:
            - PORT=${PORT}
            - MONGO_URI=${MONGO_URI}
            - TOKEN_KEY=${TOKEN_KEY}
            - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
            - AWS_BUCKET_REGION=${AWS_BUCKET_REGION}
            - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
            - AWS_SECRET_KEY=${AWS_SECRET_KEY}
        volumes:
            - ./backend:/app
            - /app/node_modules
        networks:
            - webappnetwork
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - 27037:27017
        command: mongod
        networks:
            - webappnetwork
networks:
    webappnetwork:
        driver: bridge