version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_SERVER=${REACT_APP_API_SERVER}
    volumes:
      - /app/node_modules
      - ./frontend:/app
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - '5050:4040'
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - TOKEN_KEY=${TOKEN_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_BUCKET_REGION=${AWS_BUCKET_REGION}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
    volumes:
      - /app/node_modules
      - ./backend:/app
