openapi: 3.0.3

info:
  title: Planty
  description: Planty backend OpenApi documentation
  version: 1.0.0

externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io

tags:
  - name: Register
    description: New user registration
  - name: Login
    description: User login
  - name: Users
    description: User profile
  - name: Plants
    description: Operations with plants
  - name: Potting mixes
    description: Operations with potting mixes
  - name: Plant requests
    description: Operations with plant requests

paths:
  /api/register:
    $ref: "./resources/register.yaml"
  /api/login:
    $ref: "./resources/login.yaml"
  /api/users:
    $ref: "./resources/users.yaml"
  /api/plants:
    $ref: "./resources/plants.yaml"
  /api/admin/new-plant:
    $ref: "./resources/new-plant.yaml"
  /api/potting-mixes:
    $ref: "./resources/potting-mixes.yaml"
  /api/new-potting-mix:
    $ref: "./resources/new-potting-mix.yaml"
  /api/plant-request:
    $ref: "./resources/requests.yaml"

components:
  schemas:
    $ref: "./schemas/_index.yaml"
  responses:
    $ref: "./responses/_index.yaml"
  securitySchemes:
    bearerAuth:            
      type: http
      scheme: bearer
      bearerFormat: JWT
