openapi: 3.0.3

info:
  title: Planty
  description: Planty backend OpenApi documentation
  version: 1.0.0

externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io

tags:
  - name: Register
    description: New user registration
  - name: Login
    description: User login
  - name: Users
    description: User profile

paths:
  /api/register:
    $ref: "./resources/register.yaml"
  /api/login:
    $ref: "./resources/login.yaml"
  /api/users:
    $ref: "./resources/users.yaml"

components:
  schemas:
    $ref: "./schemas/_index.yaml"
  responses:
    $ref: "./responses/_index.yaml"
  securitySchemes:
    bearerAuth:            
      type: http
      scheme: bearer
      bearerFormat: JWT
